[package]
name = "beatforge-studio"
version = "0.3.0"
edition = "2021"

[dependencies]
eframe = "0.29"
cpal = "0.15"
crossbeam-channel = "0.5"
rfd = "0.15"
hound = "3.5"
symphonia = { version = "0.5", features = ["mp3", "ogg", "flac", "wav", "pcm", "aac"] }
midir = "0.10"

[profile.release]
opt-level = 3
lto = true
