//! Synth presets for the subtractive synthesizer.
//! Each preset configures oscillators, filter, envelopes, and LFO
//! to produce a specific type of sound.

use crate::synth::{SynthParams, Waveform, FilterType, LfoTarget};

pub struct Preset {
    pub name: &'static str,
    pub category: &'static str,
    pub params: SynthParams,
}

pub fn all_presets() -> Vec<Preset> {
    vec![
        // ── BASS ───────────────────────────────────────
        Preset {
            name: "808 Sub",
            category: "Bass",
            params: SynthParams {
                osc1_wave: Waveform::Sine,
                osc2_wave: Waveform::Sine,
                osc_mix: 0.0,
                osc2_detune: 0.0,
                osc2_semi: 0,
                osc2_octave: 0,
                filter_type: FilterType::Lowpass,
                filter_cutoff: 800.0,
                filter_resonance: 0.1,
                amp_attack: 0.005,
                amp_decay: 0.8,
                amp_sustain: 0.0,
                amp_release: 0.5,
                filt_attack: 0.005,
                filt_decay: 0.3,
                filt_sustain: 0.0,
                filt_release: 0.3,
                filt_env_amount: 0.4,
                lfo_rate: 0.5,
                lfo_amount: 0.0,
                lfo_wave: Waveform::Sine,
                lfo_target: LfoTarget::FilterCutoff,
                volume: 0.6,
                glide: 0.05,
                unison_voices: 1, unison_detune: 10.0, sub_osc: true, sub_level: 0.6, ring_mod: false,
            },
        },
        Preset {
            name: "Reese Bass",
            category: "Bass",
            params: SynthParams {
                osc1_wave: Waveform::Saw,
                osc2_wave: Waveform::Saw,
                osc_mix: 0.5,
                osc2_detune: 12.0,
                osc2_semi: 0,
                osc2_octave: 0,
                filter_type: FilterType::Lowpass,
                filter_cutoff: 1200.0,
                filter_resonance: 0.3,
                amp_attack: 0.01,
                amp_decay: 0.1,
                amp_sustain: 0.8,
                amp_release: 0.2,
                filt_attack: 0.01,
                filt_decay: 0.5,
                filt_sustain: 0.3,
                filt_release: 0.3,
                filt_env_amount: 0.5,
                lfo_rate: 0.3,
                lfo_amount: 0.15,
                lfo_wave: Waveform::Triangle,
                lfo_target: LfoTarget::FilterCutoff,
                volume: 0.5,
                glide: 0.03,
                unison_voices: 1, unison_detune: 15.0, sub_osc: true, sub_level: 0.5, ring_mod: false,
            },
        },
        Preset {
            name: "Acid Bass",
            category: "Bass",
            params: SynthParams {
                osc1_wave: Waveform::Square,
                osc2_wave: Waveform::Saw,
                osc_mix: 0.2,
                osc2_detune: 0.0,
                osc2_semi: 0,
                osc2_octave: -1,
                filter_type: FilterType::Lowpass,
                filter_cutoff: 400.0,
                filter_resonance: 0.7,
                amp_attack: 0.001,
                amp_decay: 0.15,
                amp_sustain: 0.0,
                amp_release: 0.05,
                filt_attack: 0.001,
                filt_decay: 0.2,
                filt_sustain: 0.0,
                filt_release: 0.1,
                filt_env_amount: 0.9,
                lfo_rate: 4.0,
                lfo_amount: 0.0,
                lfo_wave: Waveform::Sine,
                lfo_target: LfoTarget::FilterCutoff,
                volume: 0.5,
                glide: 0.02,
                unison_voices: 1, unison_detune: 10.0, sub_osc: false, sub_level: 0.5, ring_mod: false,
            },
        },
        Preset {
            name: "Wobble Bass",
            category: "Bass",
            params: SynthParams {
                osc1_wave: Waveform::Saw,
                osc2_wave: Waveform::Square,
                osc_mix: 0.4,
                osc2_detune: 5.0,
                osc2_semi: 0,
                osc2_octave: 0,
                filter_type: FilterType::Lowpass,
                filter_cutoff: 600.0,
                filter_resonance: 0.5,
                amp_attack: 0.01,
                amp_decay: 0.1,
                amp_sustain: 0.9,
                amp_release: 0.1,
                filt_attack: 0.01,
                filt_decay: 0.1,
                filt_sustain: 0.5,
                filt_release: 0.2,
                filt_env_amount: 0.3,
                lfo_rate: 3.0,
                lfo_amount: 0.7,
                lfo_wave: Waveform::Sine,
                lfo_target: LfoTarget::FilterCutoff,
                volume: 0.5,
                glide: 0.0,
                unison_voices: 1, unison_detune: 10.0, sub_osc: false, sub_level: 0.5, ring_mod: false,
            },
        },

        // ── LEADS ──────────────────────────────────────
        Preset {
            name: "Square Lead",
            category: "Lead",
            params: SynthParams {
                osc1_wave: Waveform::Square,
                osc2_wave: Waveform::Square,
                osc_mix: 0.3,
                osc2_detune: 8.0,
                osc2_semi: 7,
                osc2_octave: 0,
                filter_type: FilterType::Lowpass,
                filter_cutoff: 3000.0,
                filter_resonance: 0.2,
                amp_attack: 0.005,
                amp_decay: 0.1,
                amp_sustain: 0.7,
                amp_release: 0.3,
                filt_attack: 0.01,
                filt_decay: 0.2,
                filt_sustain: 0.5,
                filt_release: 0.2,
                filt_env_amount: 0.3,
                lfo_rate: 5.0,
                lfo_amount: 0.1,
                lfo_wave: Waveform::Sine,
                lfo_target: LfoTarget::Pitch,
                volume: 0.4,
                glide: 0.0,
                unison_voices: 1, unison_detune: 10.0, sub_osc: false, sub_level: 0.5, ring_mod: false,
            },
        },
        Preset {
            name: "Saw Lead",
            category: "Lead",
            params: SynthParams {
                osc1_wave: Waveform::Saw,
                osc2_wave: Waveform::Saw,
                osc_mix: 0.5,
                osc2_detune: 15.0,
                osc2_semi: 0,
                osc2_octave: 0,
                filter_type: FilterType::Lowpass,
                filter_cutoff: 5000.0,
                filter_resonance: 0.15,
                amp_attack: 0.01,
                amp_decay: 0.05,
                amp_sustain: 0.8,
                amp_release: 0.2,
                filt_attack: 0.01,
                filt_decay: 0.3,
                filt_sustain: 0.6,
                filt_release: 0.3,
                filt_env_amount: 0.2,
                lfo_rate: 6.0,
                lfo_amount: 0.05,
                lfo_wave: Waveform::Sine,
                lfo_target: LfoTarget::Pitch,
                volume: 0.35,
                glide: 0.0,
                unison_voices: 5, unison_detune: 20.0, sub_osc: false, sub_level: 0.5, ring_mod: false,
            },
        },

        // ── PADS ───────────────────────────────────────
        Preset {
            name: "Warm Pad",
            category: "Pad",
            params: SynthParams {
                osc1_wave: Waveform::Saw,
                osc2_wave: Waveform::Triangle,
                osc_mix: 0.5,
                osc2_detune: 10.0,
                osc2_semi: 0,
                osc2_octave: 0,
                filter_type: FilterType::Lowpass,
                filter_cutoff: 2000.0,
                filter_resonance: 0.1,
                amp_attack: 0.5,
                amp_decay: 0.3,
                amp_sustain: 0.8,
                amp_release: 1.5,
                filt_attack: 0.8,
                filt_decay: 0.5,
                filt_sustain: 0.5,
                filt_release: 1.0,
                filt_env_amount: 0.3,
                lfo_rate: 0.5,
                lfo_amount: 0.1,
                lfo_wave: Waveform::Sine,
                lfo_target: LfoTarget::FilterCutoff,
                volume: 0.35,
                glide: 0.0,
                unison_voices: 1, unison_detune: 10.0, sub_osc: false, sub_level: 0.5, ring_mod: false,
            },
        },
        Preset {
            name: "Dark Pad",
            category: "Pad",
            params: SynthParams {
                osc1_wave: Waveform::Square,
                osc2_wave: Waveform::Saw,
                osc_mix: 0.6,
                osc2_detune: 20.0,
                osc2_semi: -12,
                osc2_octave: 0,
                filter_type: FilterType::Lowpass,
                filter_cutoff: 800.0,
                filter_resonance: 0.2,
                amp_attack: 1.0,
                amp_decay: 0.5,
                amp_sustain: 0.7,
                amp_release: 2.0,
                filt_attack: 1.2,
                filt_decay: 0.8,
                filt_sustain: 0.3,
                filt_release: 1.5,
                filt_env_amount: 0.2,
                lfo_rate: 0.3,
                lfo_amount: 0.15,
                lfo_wave: Waveform::Triangle,
                lfo_target: LfoTarget::FilterCutoff,
                volume: 0.3,
                glide: 0.0,
                unison_voices: 1, unison_detune: 10.0, sub_osc: false, sub_level: 0.5, ring_mod: false,
            },
        },

        // ── KEYS / PLUCKS ──────────────────────────────
        Preset {
            name: "Pluck",
            category: "Keys",
            params: SynthParams {
                osc1_wave: Waveform::Saw,
                osc2_wave: Waveform::Triangle,
                osc_mix: 0.3,
                osc2_detune: 3.0,
                osc2_semi: 0,
                osc2_octave: 1,
                filter_type: FilterType::Lowpass,
                filter_cutoff: 3000.0,
                filter_resonance: 0.2,
                amp_attack: 0.001,
                amp_decay: 0.3,
                amp_sustain: 0.0,
                amp_release: 0.15,
                filt_attack: 0.001,
                filt_decay: 0.15,
                filt_sustain: 0.0,
                filt_release: 0.1,
                filt_env_amount: 0.6,
                lfo_rate: 4.0,
                lfo_amount: 0.0,
                lfo_wave: Waveform::Sine,
                lfo_target: LfoTarget::FilterCutoff,
                volume: 0.45,
                glide: 0.0,
                unison_voices: 1, unison_detune: 10.0, sub_osc: false, sub_level: 0.5, ring_mod: false,
            },
        },
        Preset {
            name: "Electric Piano",
            category: "Keys",
            params: SynthParams {
                osc1_wave: Waveform::Sine,
                osc2_wave: Waveform::Triangle,
                osc_mix: 0.3,
                osc2_detune: 1.0,
                osc2_semi: 0,
                osc2_octave: 1,
                filter_type: FilterType::Lowpass,
                filter_cutoff: 4000.0,
                filter_resonance: 0.1,
                amp_attack: 0.005,
                amp_decay: 0.8,
                amp_sustain: 0.2,
                amp_release: 0.5,
                filt_attack: 0.005,
                filt_decay: 0.5,
                filt_sustain: 0.2,
                filt_release: 0.3,
                filt_env_amount: 0.3,
                lfo_rate: 4.5,
                lfo_amount: 0.05,
                lfo_wave: Waveform::Sine,
                lfo_target: LfoTarget::Amplitude,
                volume: 0.4,
                glide: 0.0,
                unison_voices: 1, unison_detune: 10.0, sub_osc: false, sub_level: 0.5, ring_mod: false,
            },
        },
        Preset {
            name: "Organ",
            category: "Keys",
            params: SynthParams {
                osc1_wave: Waveform::Sine,
                osc2_wave: Waveform::Sine,
                osc_mix: 0.4,
                osc2_detune: 0.0,
                osc2_semi: 0,
                osc2_octave: 1,
                filter_type: FilterType::Lowpass,
                filter_cutoff: 6000.0,
                filter_resonance: 0.05,
                amp_attack: 0.01,
                amp_decay: 0.05,
                amp_sustain: 0.9,
                amp_release: 0.05,
                filt_attack: 0.01,
                filt_decay: 0.1,
                filt_sustain: 0.8,
                filt_release: 0.1,
                filt_env_amount: 0.1,
                lfo_rate: 6.0,
                lfo_amount: 0.08,
                lfo_wave: Waveform::Sine,
                lfo_target: LfoTarget::Amplitude,
                volume: 0.35,
                glide: 0.0,
                unison_voices: 1, unison_detune: 10.0, sub_osc: false, sub_level: 0.5, ring_mod: false,
            },
        },

        // ── FM SYNTHESIS ───────────────────────────────
        Preset {
            name: "FM Bell",
            category: "FM",
            params: SynthParams {
                osc1_wave: Waveform::Fm,
                osc2_wave: Waveform::Sine,
                osc_mix: 0.4, // FM index
                osc2_detune: 0.0,
                osc2_semi: 0,
                osc2_octave: 1, // modulator at 2× carrier
                filter_type: FilterType::Lowpass,
                filter_cutoff: 12000.0,
                filter_resonance: 0.1,
                amp_attack: 0.001,
                amp_decay: 1.0,
                amp_sustain: 0.0,
                amp_release: 0.5,
                filt_attack: 0.001,
                filt_decay: 0.5,
                filt_sustain: 0.2,
                filt_release: 0.3,
                filt_env_amount: 0.3,
                lfo_rate: 4.0,
                lfo_amount: 0.0,
                lfo_wave: Waveform::Sine,
                lfo_target: LfoTarget::FilterCutoff,
                volume: 0.4,
                glide: 0.0,
                unison_voices: 1, unison_detune: 10.0, sub_osc: false, sub_level: 0.5, ring_mod: false,
            },
        },
        Preset {
            name: "FM Bass",
            category: "FM",
            params: SynthParams {
                osc1_wave: Waveform::Fm,
                osc2_wave: Waveform::Sine,
                osc_mix: 0.6, // high FM index for grit
                osc2_detune: 0.0,
                osc2_semi: 0,
                osc2_octave: 0, // 1:1 ratio
                filter_type: FilterType::Lowpass,
                filter_cutoff: 1500.0,
                filter_resonance: 0.2,
                amp_attack: 0.005,
                amp_decay: 0.3,
                amp_sustain: 0.4,
                amp_release: 0.15,
                filt_attack: 0.005,
                filt_decay: 0.2,
                filt_sustain: 0.2,
                filt_release: 0.15,
                filt_env_amount: 0.6,
                lfo_rate: 3.0,
                lfo_amount: 0.0,
                lfo_wave: Waveform::Sine,
                lfo_target: LfoTarget::FilterCutoff,
                volume: 0.5,
                glide: 0.03,
                unison_voices: 1, unison_detune: 15.0, sub_osc: true, sub_level: 0.5, ring_mod: false,
            },
        },
        Preset {
            name: "FM Metallic",
            category: "FM",
            params: SynthParams {
                osc1_wave: Waveform::Fm,
                osc2_wave: Waveform::Sine,
                osc_mix: 0.7,
                osc2_detune: 30.0,
                osc2_semi: 7, // non-harmonic ratio for metallic timbre
                osc2_octave: 1,
                filter_type: FilterType::Lowpass,
                filter_cutoff: 8000.0,
                filter_resonance: 0.15,
                amp_attack: 0.001,
                amp_decay: 0.4,
                amp_sustain: 0.0,
                amp_release: 0.3,
                filt_attack: 0.001,
                filt_decay: 0.3,
                filt_sustain: 0.0,
                filt_release: 0.2,
                filt_env_amount: 0.4,
                lfo_rate: 5.0,
                lfo_amount: 0.0,
                lfo_wave: Waveform::Sine,
                lfo_target: LfoTarget::FilterCutoff,
                volume: 0.35,
                glide: 0.0,
                unison_voices: 1, unison_detune: 10.0, sub_osc: false, sub_level: 0.5, ring_mod: false,
            },
        },

        // ── FX / SPECIAL ───────────────────────────────
        Preset {
            name: "Noise Sweep",
            category: "FX",
            params: SynthParams {
                osc1_wave: Waveform::Noise,
                osc2_wave: Waveform::Noise,
                osc_mix: 0.0,
                osc2_detune: 0.0,
                osc2_semi: 0,
                osc2_octave: 0,
                filter_type: FilterType::Bandpass,
                filter_cutoff: 1000.0,
                filter_resonance: 0.6,
                amp_attack: 0.5,
                amp_decay: 0.5,
                amp_sustain: 0.3,
                amp_release: 1.0,
                filt_attack: 0.01,
                filt_decay: 2.0,
                filt_sustain: 0.0,
                filt_release: 1.0,
                filt_env_amount: 0.8,
                lfo_rate: 2.0,
                lfo_amount: 0.3,
                lfo_wave: Waveform::Triangle,
                lfo_target: LfoTarget::FilterCutoff,
                volume: 0.3,
                glide: 0.0,
                unison_voices: 1, unison_detune: 10.0, sub_osc: false, sub_level: 0.5, ring_mod: false,
            },
        },
        Preset {
            name: "Stab",
            category: "FX",
            params: SynthParams {
                osc1_wave: Waveform::Saw,
                osc2_wave: Waveform::Square,
                osc_mix: 0.5,
                osc2_detune: 20.0,
                osc2_semi: 7,
                osc2_octave: 0,
                filter_type: FilterType::Lowpass,
                filter_cutoff: 5000.0,
                filter_resonance: 0.3,
                amp_attack: 0.001,
                amp_decay: 0.1,
                amp_sustain: 0.0,
                amp_release: 0.05,
                filt_attack: 0.001,
                filt_decay: 0.08,
                filt_sustain: 0.0,
                filt_release: 0.05,
                filt_env_amount: 0.5,
                lfo_rate: 4.0,
                lfo_amount: 0.0,
                lfo_wave: Waveform::Sine,
                lfo_target: LfoTarget::FilterCutoff,
                volume: 0.4,
                glide: 0.0,
                unison_voices: 1, unison_detune: 10.0, sub_osc: false, sub_level: 0.5, ring_mod: false,
            },
        },
    ]
}

/// Get presets by category
pub fn presets_by_category() -> Vec<(&'static str, Vec<Preset>)> {
    let all = all_presets();
    let categories = ["Bass", "Lead", "Pad", "Keys", "FM", "FX"];
    let mut result = Vec::new();
    for &cat in &categories {
        let presets: Vec<Preset> = all.iter()
            .filter(|p| p.category == cat)
            .map(|p| Preset { name: p.name, category: p.category, params: p.params.clone() })
            .collect();
        result.push((cat, presets));
    }
    result
}
